---
stages:
  - build
  - deploy

build-image:
  stage: build
  variables:
    TARGET_DIR: 40_nextcloud-magenta
    DEPLOY: "true"
    PKR_VAR_image_tag: "dev"
    PKR_VAR_APP_FILES_VIDEOPLAYER_TAG: ""
    PKR_VAR_APP_FILES_ZIP_TAG: "nmc01.00.00"
    PKR_VAR_APP_FILES_DOWNLOADLIMIT_TAG: "1.0.1"
    PKR_VAR_APP_MONTHLY_STATUS_EMAIL_TAG: "nmc01.00.02"
    PKR_VAR_APP_PHOTOS_TAG: "nmc01.00.08"
    PKR_VAR_APP_TEXT_TAG: "nmc01.00.04"
    PKR_VAR_APP_NMC_FIRSTRUNWIZARD_TAG: "nmc01.00.00"
    PKR_VAR_APP_NMC_FILES_ACTIVITY_TAG: "nmc01.00.04"
    PKR_VAR_APP_ACTIVITY_TAG: "nmc01.00.01"
    PKR_VAR_APP_NMC_WELCOME_POPUP_TAG: "nmc01.00.03"
    PKR_VAR_APP_NMC_EMAIL_TEMPLATE_TAG: "nmc01.00.15"
    PKR_VAR_APP_QUOTA_WARNING_TAG: "nmc01.00.00"
    PKR_VAR_NC_VERSION: "22.2.0"
    PKR_VAR_NC_TAG: "nmcrel22.2.0-21"
    PKR_VAR_theme_tag: $CI_COMMIT_TAG
  trigger:
    project: nextmagentacloud/images
    branch: master
    strategy: depend
  only:
    - /^dev1-.*$/

deploy-dev1:
  stage: deploy
  needs:
    - job: build-image
  variables:
    DEPLOY_STAGE: "dev1"
    DEPLOY: "true"
    THEME_TAG: $CI_COMMIT_TAG
  trigger:
    project: nextmagentacloud/deployment
    branch: master
    strategy: depend
  only:
    - /^dev1-.*$/
