---
stages:
  - build
  - deploy

build-image:
  stage: build
  variables:
    TARGET_DIR: 40_nextcloud-magenta
    DEPLOY: "true"
    PKR_VAR_image_tag: "dev"
    PKR_VAR_theme_tag: $CI_COMMIT_TAG
  trigger:
    project: nextmagentacloud/images
    branch: master
    strategy: depend
  only:
    - /^dev1-.*$/

deploy-dev1:
  stage: deploy
  needs:
    - job: build-image
  variables:
    DEPLOY_STAGE: "dev1"
    DEPLOY: "true"
    THEME_TAG: $CI_COMMIT_TAG
  trigger:
    project: nextmagentacloud/deployment
    branch: master
    strategy: depend
  only:
    - /^dev1-.*$/
